name: cool_stepper_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cool_stepper:
    path: ../
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
